// Comprehensive list of food ingredients relevant for GERD acute checker
// Each ingredient has a name and a category for potential future grouping

const ingredients = [
  // Fruits
  "Apple",
  "Banana",
  "Blueberry",
  "Cherry",
  "Cranberry",
  "Grape",
  "Kiwi",
  "Lemon",
  "Lime",
  "Mango",
  "Melon",
  "Orange",
  "Papaya",
  "Peach",
  "Pear",
  "Pineapple",
  "Plum",
  "Raspberry",
  "Strawberry",
  "Watermelon",

  // Vegetables
  "Asparagus",
  "Broccoli",
  "Brussels sprouts",
  "Cabbage",
  "Carrot",
  "Cauliflower",
  "Celery",
  "Cucumber",
  "Eggplant",
  "Green beans",
  "Kale",
  "Lettuce",
  "Mushroom",
  "Onion",
  "Peas",
  "Potato",
  "Pumpkin",
  "Spinach",
  "Sweet potato",
  "Tomato",
  "Zucchini",

  // Grains and cereals
  "Brown rice",
  "Oats",
  "Quinoa",
  "White rice",
  "Whole wheat bread",
  "Corn",
  "Barley",
  "Rye",
  "Millet",
  "Buckwheat",

  // Dairy and alternatives
  "Butter",
  "Cheese",
  "Cream",
  "Milk",
  "Yogurt",
  "Almond milk",
  "Soy milk",
  "Coconut milk",

  // Meats and proteins
  "Beef",
  "Chicken",
  "Egg",
  "Fish",
  "Lamb",
  "Pork",
  "Shellfish",
  "Tofu",
  "Turkey",
  "Venison",

  // Beverages
  "Coffee",
  "Green tea",
  "Herbal tea",
  "Milkshake",
  "Orange juice",
  "Soda",
  "Water",
  "Wine",
  "Beer",

  // Spices and condiments
  "Basil",
  "Black pepper",
  "Cinnamon",
  "Garlic",
  "Ginger",
  "Honey",
  "Mint",
  "Mustard",
  "Nutmeg",
  "Oregano",
  "Paprika",
  "Parsley",
  "Salt",
  "Sugar",
  "Turmeric",
  "Vinegar",

  // Sweets and snacks
  "Chocolate",
  "Cookies",
  "Ice cream",
  "Pastry",
  "Candy",
  "Cake",
  "Chips",

  // Oils and fats
  "Canola oil",
  "Coconut oil",
  "Olive oil",
  "Vegetable oil",

  // Others
  "Avocado",
  "Coconut",
  "Peanut",
  "Sesame",
  "Sunflower seeds",
  "Walnut",
  "Almond",
  "Cashew",
  "Hazelnut",
  "Chilli",
];
